name: Java CI test
on:
  push:
    branches:
      - main   
  # Enable manual execute
  workflow_dispatch:
  # Execute every 24 hours
  schedule: 
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/jar
      - name: download artifact
        uses: actions/download-artifact@main
        with:
          name: Package
          path: public
